version: '2'

services:
  jenkins:
    image: jenkins-ps
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/abennett/.ssh:/var/jenkins_home/.ssh
    group_add:
      - "999"
    links:
      - registry:registry
    depends_on:
      - registry
  registry:
    image: registry:2
    hostname: registry
    ports:
      - "5000:5000"
  registry-ui:
    image: hyper/docker-registry-web
    ports:
      - "8088:8080"
    links:
      - registry:registry
    depends_on:
      - registry
    environment:
      - REGISTRY_URL=http://registry:5000/v2
      - REGISTRY_NAME=localhost:5000
  # app:
  #   image: jenkins-docker-app
  #   build:
  #     context: ./app
  #   ports:
  #     - "2000:2000"
  #   links:
  #     - api:api
  #   depends_on:
  #     - api
  #   environment:
  #     - APP_PORT=2000
  # api:
  #   image: jenkins-docker-api
  #   build:
  #     context: ./api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - APP_PORT=3000
